#!/bin/sh

cd ~
curl --remote-name https://raw.githubusercontent.com/gcdigital-gcnumerique/non-dev-laptop/master/mac
curl --remote-name https://raw.githubusercontent.com/gcdigital-gcnumerique/non-dev-laptop/master/Brewfile
/usr/bin/env bash mac 2>&1 | tee ~/laptop.log